### ISSUE TITLE
Transit Gateway

### ISSUE THREAD

**Issue by duboiss** [Zhenye-Na/aws-certs-cheatsheet#17]
I compared the VPC cheatsheet with the content of the course I am also taking. I noticed that "Transit Gateway" was missing.
I just checked, this service is in the exam.
Would you like me to make a PR to add this component or would you rather take care of it?

Thank you very much for your useful cheatsheets :)

**Comment by Zhenye-Na** [comment]
Hi Steven @duboiss,

Thanks for your comment.

It will be fantastic if you could make a PR to add those contents.

**Comment by Zhenye-Na** [comment]
merged in https://github.com/Zhenye-Na/aws-certs-cheatsheet/pull/19
